heroku/heroku-apps

- commands/info.js
- package.json
for deleted apps, the call to dynos and collaborators will fail. This is fine, the data should just not be displayed for those.
> fix output when only partial data is returned

- commands/info.js
- package.json
Reverts heroku/heroku-apps#3
want to revert this for a bit until I'm sure all clients have node 4
> Revert "fix output when only partial data is returned"

- commands/ps/index.js
- test/commands/ps/index.js
`heroku ps` shows a list of all running dynos by type.
But when there's a lot of them, it can be hard to know how many there are. Especially if they are one-off.
> Show dyno count in ps

- lib/buildpacks.js
- test/commands/buildpacks/add.js
- test/commands/buildpacks/index.js
* We were translating the add url like the following
https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/ruby.tgz
=> heroku/ruby
This causes problems when heroku/ruby is not mapped in the API.
We are now just passing the URL straight through and letting API
do the translation for us.
> Allow the url to pass through unmodified to add

- commands/apps/create.js
Happened to spot this whilst referring to the output of `heroku apps:create --help`.
Whilst I was here I scanned the help text for the other commands using a spell-checker, but didn't find any other obvious mistakes.
> Correct a typo in the app:create help text

- commands/releases/status_helper.js
- test/commands/releases/index.js
- test/commands/releases/info.js
The current status wording is inconsistent with the one used for builds and app setups.
This allows both wordings so we can change it in API. I will remove the old one later on.
> Update release status wording

- commands/releases/status_helper.js
- test/commands/releases/info.js
API now handles all releases with succeeded/failed.
> Remove success/failure case

- commands/regions/index.js
- package.json
- test/commands/regions/index.js
Minor improvements: Add flag `--private` to shows only private runtimes and flag `--common` to show only common runtimes.
/cc @heroku/dogwood @heroku/cedar
> Add filter for private and common runtimes

- commands/apps/info.js
- test/commands/apps/info.js
@dickeyxxx - please review, I double checked and the ruby code was underscores not dashes in variable names.
> For shell output use underscore instead of slugify

- commands/releases/index.js
- commands/releases/info.js
- commands/releases/status_helper.js
- test/commands/releases/index.js
- test/commands/releases/info.js
We will soon create all releases as pending, regardless of the presence of release phase.
So we need to change the wording here, as a pending release doesn't mean we're running release phase anymore.
@dickeyxxx @ransombriggs I'd need to be able to fetch the slug for a release when looking up it's description, to know if it has a release phase command or not (and avoid showing "release command running" when there isn't any). I'm facing javascript/yield issues when doing so though. Could you advise me on the best way to do that?
> Show any queued release as pending

- commands/ps/index.js
- test/commands/ps/index.js
Cedar and Dogwood are both sending back IPs, but they're not printed in `heroku ps -x` result. You can check out it's returned with `heroku ps -x --json`. This PR is to show it in `heroku ps -x`.
Following is just a memo:
Currently, dogwood _may_ be returning incorrect IPs (it's like `"10.0.155.64/20"` right now), which they're looking into.
These are different between cedar (above) and dogwood (below) currently in `extended`. For cedar, `instance` is referring ion instance id, but for dogwood, it's referring AWS instance id. Also, for dogwood, az and port and route (route_id, maybe not available on dogwood?) are not available.
```
"extended": {
"az": "us-east-1e",
"instance": "1146464",
"ip": "10.61.195.157",
"port": "38320",
"region": "us",
"route": …
```
> Add IP addresses in the result of heroku ps -x

- commands/releases/index.js
- commands/releases/status_helper.js
- test/commands/releases/index.js
All releases will soon be created as pending, and be marked as successful once sent to the KPI.
This fixes displaying a pending release if it doesn't have a slug (which can happen for a newly created app).
> Handle pending releases without a slug

- commands/apps/info.js
- test/commands/apps/info.js
@RasPhilCo could you review?  This fixes a bug I introduced when refactoring to add the `acm` variant.  Basically now I do both a request for extended & acm and merge the acm attribute into the extended response when it is passed.
> Merge acm with extended to fix json bug

- package.json
- test/commands/keys/add.js
This fixes the test suite when stdin is not a tty (during `np` basically), can be verified by running `echo '' | npm test`
> Fix tests when stdin is not a tty

- commands/ps/index.js
- commands/ps/scale.js
- commands/ps/type.js
- test/commands/ps/index.js
- test/commands/ps/scale.js
- test/commands/ps/type.js
Hi @dickeyxxx and @ransombriggs! For compliance reasons, we need to display the dynos for apps that are in Private Spaces as "Shield-*" sizes. So dynos that would normally display as "Private-M" or "Private-L" will now display as "Shield-M" and "Shield-L" respectively for apps that are in Shielded Private Spaces.
> Display dynos for apps in shielded spaces as Shield dynos

- commands/releases/info.js
- commands/releases/output.js
- lib/releases.js
- package.json
- test/commands/releases/info.js
- test/commands/releases/output.js
- yarn.lock
@dmathieu I used `pipe` and `std-mocks` to stream the output.  I also did the refactor that I described in the original PR so that `info` and `output` treat the `release` arg the same.
> Use pipe to process.stdout instead of cli.log & refactor into finder

- commands/releases/info.js
- commands/releases/output.js
- commands/releases/rollback.js
- index.js
- lib/releases.js
- package.json
- test/commands/releases/info.js
- test/commands/releases/output.js
- yarn.lock
This command looks for the availability of an `output_stream_url` field, which will be a busl stream, and fetchs the log data from there.
cc @jbyrum @heroku/devex
> Introduce new `releases:output` command

- commands/apps/favorites/add.js
- commands/apps/favorites/index.js
- commands/apps/favorites/remove.js
- test/commands/apps/favorites/add.js
- test/commands/apps/favorites/index.js
- test/commands/apps/favorites/remove.js
We're currently working on letting users favorite other resources in addition to apps. Since the favorites API was very app-specific, we recently released a backwards-compatible update to longboard that will allow it to work with other resources. This PR updates the CLI to work with the new API format.
Please let me know if you have any questions or concerns about these changes. Thanks!
> Change favorites commands to match new longboard API

- commands/releases/output.js
- commands/releases/rollback.js
- test/commands/releases/output.js
- test/commands/releases/rollback.js
It can take a few seconds to create the release output stream. During that time, calling it will return a 404.
Send a nicer error message if that happens, until we can properly retry. See #174.
> Display a message telling to retry in case of release output 404

- src/commands/auth/logout.js
- test/commands/auth/logout.js
@dickeyxxx could you review?  this is to fix https://github.com/heroku/prodsec/issues/1
> Use heroku-cli-util.logout to get auth clearing

- src/status_helper.js
- test/commands/releases/index.js
- test/commands/releases/info.js
This was introduced to be consistent with releases not running concurrently.
That project never came to be though.
Closes #192
> Make release pending wording consistent

- src/commands/releases/index.js
- test/commands/releases/index.js
Fixing a bug introduced in https://github.com/heroku/heroku-apps/pull/216. I noticed that the previous fix was not taking all ANSI color sequences into account when calculating the lengths. The effect of this is that the table output will be still be aligned, but too narrow.
In the original implementation that stretched over `heroku-apps` and `heroku-cli-util` the ANSI stripping was done implicitly through https://github.com/heroku/heroku-cli-util/blob/v8.0.0/lib/table.js#L74. I forgot to include that when migrating that code to the current implementation.
Here I am creating a fix which is to call `stripAnsi(formattedValue)` when calculating the optimization lengths.
The rest of the PR is for increasing testability of the code. The older tests won't fail for this scenario since colors are …
> Strip ANSI characters when fitting terminal width

- package.json
- src/commands/apps/create.js
- test/commands/apps/create.js
This implementation supports a single `setup` entry in the YAML file, for specifying addons. We will expand this to support the rest of the planned heroku.yml functionality in future pull requests.
> Add a `--manifest` option for beta users to support heroku.yml files.
