commands/info.js
package.json

Revert the revert when v4 is fully out

Revert "Revert "fix output when only partial data is returned""

---

commands/config/set.js
test/commands/config/set.js

config:set updates

---

commands/ps/index.js
package.json
test/commands/ps/index.js

ready for review @ransombriggs 
cc @sclasen

fix sorting of ps output

---

lib/buildpacks.js
test/commands/buildpacks/add.js

@dickeyxxx review?  fixes heroku/heroku-apps#34 which should have been throwing an error.

Fix bug in buildpacks:add when index is zero

---

commands/ps/index.js
test/commands/ps/index.js

Changed variable name in the ps sub-command

---

commands/releases/index.js

Don't show full email address for add-on releases

---

commands/features/index.js
commands/labs/index.js

Remove the spread operator from labs / features

---

commands/apps/info.js
package.json
test/commands/apps/info.js

also cleaned up dogwood code a bit

add pipeline to apps:info

---

commands/apps/create.js
commands/apps/destroy.js
commands/domains/add.js
commands/domains/clear.js
commands/domains/remove.js
commands/features/disable.js
commands/features/enable.js
commands/features/index.js
commands/labs/index.js
commands/ps/scale.js
commands/stack/set.js
package.json

this is so it will work with the new app style output

use cli.colors.app()

---

commands/config/index.js
commands/config/set.js
commands/config/unset.js
package.json
test/commands/config/set.js
test/commands/config/unset.js

added release back in and use consistent colors

improve config:* UX

---

commands/dashboard.js
commands/keys/add.js
test/commands/keys/add.js

Add yes command line flag

---

commands/releases/index.js
commands/releases/info.js
commands/releases/status_helper.js
test/commands/releases/index.js
test/commands/releases/info.js

The variant will disappear when this is implemented in both dashboard and cli.
I'll open another PR to remove it when it's that time.

Display release status

---

commands/ps/index.js
test/commands/ps/index.js

@dickeyxxx review me, but do not merge

Change free usage to be based off of account quota

---

commands/domains/add.js
commands/domains/wait.js
index.js
lib/domains_wait.js
package.json
test/commands/domains/wait.js

@dickeyxxx review me ? (but do not merge, still waiting on sign-off for the new language).  The functionality will probably not change though.  An example of old vs new behavior can be found here https://gist.github.com/ransombriggs/134d6977b505f95e39804c1b3578b9c2 .

Add stable domains:add extra functionality

---

commands/domains/add.js
test/commands/domains/add.js

Properly escape domains:wait example command

---

commands/drains/remove.js

This fixes https://github.com/heroku/heroku-apps/issues/112.
/cc @dickeyxxx

Update usage of `drains:remove` to remove by logplex token

---

commands/releases/index.js
test/commands/releases/index.js

Show which is the current release when listing them

---

commands/apps/index.js
test/commands/apps/index.js

this is a bit cleaner and more efficient

use /users/~/apps endpoint

---

commands/drains/remove.js

Fixes https://github.com/heroku/cli/issues/324

fix help text

---

commands/dashboard.js
commands/notifications/index.js
commands/ps/index.js

solarized dark does not display gray in iterm2
cc @ransombriggs

use dim instead of gray

---

commands/ps/stop.js
test/commands/ps/stop.js

Parse ps:stop body into JSON when error

---

commands/apps/destroy.js
commands/apps/info.js
test/commands/apps/destroy.js
test/commands/apps/info.js

Set context.app in info & destory for arg case

---

commands/apps/errors.js
test/commands/apps/errors.js

Trap bad request response when web missing

---

commands/releases/info.js
test/commands/releases/info.js

Closes #147
cc @heroku/build @dickeyxxx @ransombriggs @dmcinnes

Use API V3 in releases info

---

commands/apps/errors.js
test/commands/apps/errors.js

show source for dyno types

---

commands/ps/stop.js
test/commands/ps/stop.js

note that currently this does not work with dyno types

use apiv3 for ps:stop

---

commands/apps/info.js
test/commands/apps/info.js

Change apps:info ACM => Auto Cert Mgmt

---

commands/buildpacks/set.js

@dickeyxxx could you review?  @jkutner had suggested a long time ago in another repo, but I missed the suggestion

Update example to use short-hand notation

---

commands/apps/info.js
test/commands/apps/info.js

Do not print `undefined` when no extended info

---

commands/apps/stacks/set.js
lib/buildpacks.js
lib/push.js

Use remote flag in git push suggestion if passed

---

commands/domains/wait.js
test/commands/domains/wait.js

Make hostname optional to match {pg,addons}:wait

---

circle.yml

brings CI times down from 2 minutes to 19 seconds!

circle 2.0

---

circle.yml
commands/apps/create.js
commands/apps/index.js
commands/dashboard.js
package.json
test/commands/apps/index.js
yarn.lock

@dickeyxxx Did I get close 🎯  ? Use v6 flags -> make it look like a v5 flag -> for a v5 command -> to be converted to a v6 command 😁 
ref https://github.com/heroku/cli-engine/issues/126

Change org flag to team

---

commands/apps/create.js
commands/apps/index.js

@ransombriggs https://github.com/heroku/heroku-apps/pull/176

use wantsOrg

---

commands/auth/login.js
package.json
yarn.lock

closes https://github.com/heroku/cli/issues/313

Add login expires-in flag

---

commands/apps/create.js
commands/apps/index.js
commands/apps/info.js
commands/apps/open.js
commands/apps/rename.js
commands/apps/stacks/set.js
commands/buildpacks/add.js
commands/buildpacks/index.js
commands/buildpacks/set.js
commands/config/get.js
commands/config/set.js
commands/config/unset.js
commands/domains/index.js
commands/keys/add.js
commands/keys/remove.js
commands/ps/index.js
commands/ps/restart.js
commands/ps/scale.js
commands/ps/stop.js
commands/releases/index.js

for the dev center documentation

markdown changes for help

---

commands/dashboard.js

[wip] show help by default

---

src/commands/dashboard.js
test/commands/dashboard.js

@dickeyxxx Or we can filter `undefined`'s after the call.

fix dashboard favorites call

---

src/commands/apps/create.js
test/commands/apps/create.js

Closes https://github.com/heroku/cli-engine/issues/225

add json output to apps:create

---

package.json
src/commands/apps/create.js
src/commands/apps/index.js
yarn.lock

add flag completions

---

package.json
src/commands/domains/index.js
test/commands/domains/index.js
yarn.lock

Added DNS Record Type to domains output

---

src/commands/ps/index.js
test/commands/ps/index.js

Closes https://github.com/heroku/cli/issues/615

sort dynos before printing

---

src/commands/labs/disable.js
src/commands/labs/disable.test.js
test/jest.js

Fixes https://github.com/heroku/cli/issues/598

add strict-tls disable warning & confirmation

---

src/commands/releases/index.js
test/commands/releases/index.js

This is a two-part fix:
- ~~First part is the fix in https://github.com/heroku/heroku-cli-util/pull/114 where I create a way to pass an options.optimizeKey to `cli.table` which will calculate a optimizationWidth consisting of the width of all other columns + column separators. And then pass this as a third paramater to the formatter for the optimization column.~~
- First part is this PR which expands the `descriptionWithStatus` formatter to use a calculated optimizationWidth to figure out exactly how wide the description column should be to fit the terminal width. I remove the arbitrary width 60 from the calculation and replaced it with a dynamic value. Special care is taken to use the status width _before_ appending the ANSI color tags instead of `sc` like the current code does.
- Second …

Adjust 'heroku releases' output to fit terminal width

---

src/commands/apps/info.js
test/commands/apps/info.js

So people know the next build will change their stack.

Show stack change in app info

---

src/commands/apps/create.js
src/commands/apps/index.js
src/commands/apps/info.js
test/commands/apps/create.js
test/commands/apps/index.js
test/commands/apps/info.js

This adds the requisite flag for an upcoming feature. The API changes for this have yet to be implemented and this may change a bit depending on https://github.com/heroku/dogwood/issues/1743. Just getting this up for general review and so we have something to reference for the changeset.

iwa: Add --internal-routing flag for app creation
